const subject = ['HTML','JS','CSS','Angular','Java','J2ee'];
console.log("length after Addind/pushing elements ",subject.push('Python','SQL'));
console.log("after pushing :",subject);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(subject));
console.log("-------------------------");
console.log("Is element is present :",subject.includes('JS'));
console.log("-------------------------");
console.log("Poped element is :",subject.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",subject.unshift("DS","C"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",subject.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",subject.splice(1,0,"Big Data"));
console.log("-------------------------");
const nSub = subject.slice(2,4);
console.log("Sliced Array is",nSub);
console.log("-------------------------");
console.log("Index of Specified element is",subject.indexOf("Java",3));
console.log("-------------------------");
const strSub = subject.join("-");
console.log("String of array with seperator between elements by using join ",strSub);
console.log("-------------------------");


const shoes = ['Puma','Bata','Lunars','Adidas','Nike'];
console.log("length after Addind/pushing elements ",shoes.push('Python','SQL'));
console.log("after pushing :",shoes);

console.log("-------------------------");
console.log('Is this Array :',Array.isArray(shoes));
console.log("-------------------------");
console.log("Is element is present :",shoes.includes('Lunars'));
console.log("-------------------------");
console.log("Poped element is :",shoes.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",shoes.unshift("Gucci"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",shoes.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",shoes.splice(1,0,"Sparx"));
console.log("-------------------------");
const nShoes = shoes.slice(2,4);
console.log("Sliced Array is",nShoes);
console.log("-------------------------");
console.log("Index of Specified element is",shoes.indexOf("Paragon",3));
console.log("-------------------------");
const strShoes = shoes.join("-");
console.log("String of array with seperator between elements by using join ",strShoes);
console.log("-------------------------");


const planets = ['Earth','Mercury','Mars','Jupitar'];
console.log("length after Addind/pushing elements ",planets.push('Python','SQL'));
console.log("after pushing :",planets);

console.log("-------------------------");
console.log('Is this Array :',Array.isArray(planets));
console.log("-------------------------");
console.log("Is element is present :",planets.includes('Pluto'));
console.log("-------------------------");
console.log("Poped element is :",planets.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",planets.unshift("Venus"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",planets.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",planets.splice(1,0,"Saturn"));
console.log("-------------------------");
const nPlanets = planets.slice(2,4);
console.log("Sliced Array is",nPlanets);
console.log("-------------------------");
console.log("Index of Specified element is",planets.indexOf("Neptune",3));
console.log("-------------------------");
const strPlanets = planets.join("-");
console.log("String of array with seperator between elements by using join ",strPlanets);
console.log("-------------------------");


const continents = ['Asia','Africa','Europe','Australia'];
console.log("length after Addind/pushing elements ",continents.push('North America'));
console.log("after pushing :",continents);

console.log("-------------------------");
console.log('Is this Array :',Array.isArray(continents));
console.log("-------------------------");
console.log("Is element is present :",continents.includes('JS'));
console.log("-------------------------");
console.log("Poped element is :",continents.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",continents.unshift("Antartica"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",continents.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",continents.splice(1,0,"South America"));
console.log("-------------------------");
const nContinents = continents.slice(2,4);
console.log("Sliced Array is",nContinents);
console.log("-------------------------");
console.log("Index of Specified element is",continents.indexOf("Antartica",0));
console.log("-------------------------");
const strContinents = continents.join("-");
console.log("String of array with seperator between elements by using join ",strContinents);
console.log("-------------------------");


const lang = ['Kannada','Hindi','Samskrit','English','Telagu'];
console.log("length after Addind/pushing elements ",lang.push('Tamil'));
console.log("after pushing :",lang);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(lang));
console.log("-------------------------");
console.log("Is element is present :",lang.includes('English'));
console.log("-------------------------");
console.log("Poped element is :",lang.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",lang.unshift("Malyalum"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",lang.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",lang.splice(1,0,"Chinese"));
console.log("-------------------------");
const nlang = lang.slice(2,4);
console.log("Sliced Array is",nlang);
console.log("-------------------------");
console.log("Index of Specified element is",lang.indexOf("Telagu",2));
console.log("-------------------------");
const strlang = lang.join("-");
console.log("String of array with seperator between elements by using join ",strlang);
console.log("-------------------------");


const branch = ['CSE','IS','ECE','EEE'];
console.log("length after Addind/pushing elements ",branch.push('Python','SQL'));
console.log("after pushing :",branch);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(branch));
console.log("-------------------------");
console.log("Is element is present :",branch.includes('JS'));
console.log("-------------------------");
console.log("Poped element is :",branch.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",branch.unshift("Civil"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",branch.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",branch.splice(1,0,"Mech"));
console.log("-------------------------");
const nBranch = branch.slice(2,4);
console.log("Sliced Array is",nBranch);
console.log("-------------------------");
console.log("Index of Specified element is",branch.indexOf("EEE",1));
console.log("-------------------------");
const strBranch = branch.join("-");
console.log("String of array with seperator between elements by using join ",strBranch);
console.log("-------------------------");



const currency = ['Rupees','Dollar','yen','Euro'];
console.log("length after Addind/pushing elements ",currency.push('Pound'));
console.log("after pushing :",currency);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(currency));
console.log("-------------------------");
console.log("Is element is present :",currency.includes('Pound'));
console.log("-------------------------");
console.log("Poped element is :",currency.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",currency.unshift("Yen"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",currency.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",currency.splice(1,0,"Peso"));
console.log("-------------------------");
const nCurrency = currency.slice(2,4);
console.log("Sliced Array is",nCurrency);
console.log("-------------------------");
console.log("Index of Specified element is",currency.indexOf("Rupee",1));
console.log("-------------------------");
const strCurrency = currency.join("-");
console.log("String of array with seperator between elements by using join ",strCurrency);
console.log("-------------------------");


const countries = ['India','USA','Russia','Japan'];
console.log("length after Addind/pushing elements ",countries.push('China'));
console.log("after pushing :",countries);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(countries));
console.log("-------------------------");
console.log("Is element is present :",countries.includes('Russia'));
console.log("-------------------------");
console.log("Poped element is :",countries.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",countries.unshift("Sri Lanka"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",countries.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",countries.splice(1,0,"Australia"));
console.log("-------------------------");
const nCountries = countries.slice(2,4);
console.log("Sliced Array is",nCountries);
console.log("-------------------------");
console.log("Index of Specified element is",countries.indexOf("USA",1));
console.log("-------------------------");
const strCountries = countries.join("-");
console.log("String of array with seperator between elements by using join ",strCountries);
console.log("-------------------------");




const states = ['Karnataka','Maharastra','Tamil Nadu','Andra pradesh'];
console.log("length after Addind/pushing elements ",states.push('Goa'));
console.log("after pushing :",states);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(states));
console.log("-------------------------");
console.log("Is element is present :",states.includes('Mharastra'));
console.log("-------------------------");
console.log("Poped element is :",states.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",states.unshift("Madhya Pradesh"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",states.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",states.splice(1,0,"Punjab"));
console.log("-------------------------");
const nStates = states.slice(2,4);
console.log("Sliced Array is",nStates);
console.log("-------------------------");
console.log("Index of Specified element is",states.indexOf("Kerala",1));
console.log("-------------------------");
const strStates = states.join("-");
console.log("String of array with seperator between elements by using join ",strStates);
console.log("-------------------------");

const week = ['Sunday','Monday','Tuesday','Wednesday'];
console.log("length after Addind/pushing elements ",week.push('Saturday'));
console.log("after pushing :",week);
console.log("-------------------------");
console.log('Is this Array :',Array.isArray(week));
console.log("-------------------------");
console.log("Is element is present :",week.includes('Russia'));
console.log("-------------------------");
console.log("Poped element is :",week.pop());
console.log("-------------------------");
console.log(" length after Unshifting/adding elements at last",week.unshift("Sri Lanka"));
console.log("-------------------------");
console.log("Removed/Shifted element from start of array",week.shift());
console.log("-------------------------");
console.log("Spliced elements(remove elements and add new elemenrs to specified index)",week.splice(1,0,"Australia"));
console.log("-------------------------");
const nWeek = week.slice(2,4);
console.log("Sliced Array is",nWeek);
console.log("-------------------------");
console.log("Index of Specified element is",week.indexOf("USA",1));
console.log("-------------------------");
const strWeek = week.join("-");
console.log("String of array with seperator between elements by using join ",strWeek);
console.log("-------------------------");
